name = "QuasinormalModes"
uuid = "7b4b3212-f72a-4ba2-afa8-103f0bfb7cd6"
authors = ["Lucas Timotheo Sanches <lucas.t@ufabc.edu.br>"]
version = "1.0.0"

[deps]
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
PolynomialRoots = "3a141323-8675-5d76-9d11-e1df1406c778"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
SymEngine = "123dc426-2d89-5057-bbad-38513e3affd8"
TaylorSeries = "6aa5eb33-94cf-58f4-a9d0-e4b2c4fc25ea"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
NLsolve = "^4.5.1"
PolynomialRoots = "^1.0.0"
Polynomials = "^2.0.0"
Roots = "^1.0.8"
SafeTestsets = "^0.0.1"
SymEngine = "^0.8.2"
TaylorSeries = "^0.10.11"
julia = "^1.6"
